### ISSUE TITLE
Removed elements are still validated after initial validation

### ISSUE THREAD

**Issue by sh-benevity** [Vinccool96/vee-validate-legacy#1]
Hi,

Which vee-validate version was used to create vee-validate-legacy?

I am seeing what appears to be [this old issue](https://github.com/logaretm/vee-validate/issues/170). 
If an element is validated and marked as invalid and then removed based on the v-if condition, it is still in the error validation list.

I am using:
VueJs: 3.4.15
vee-validate-legacy: 1.0.1

**Comment by sh-benevity** [comment]
@Vinccool96 I've created a pull request to fix this issue. Can you please approve/merge it?

https://github.com/Vinccool96/vee-validate-legacy/pull/2

**Comment by sh-benevity** [comment]
@Vinccool96, thank you!

**Comment by Vinccool96** [comment]
You're welcome. It should be updated when pulling the new version.
